In [2]:
import numpy as np

In [6]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [10]:
a.shape

(3, 5)

In [11]:
a.ndim

2

In [12]:
a.size

15

In [13]:
a.nbytes

60

In [19]:
c = np.arange(2,10,2)
print(c)

[2 4 6 8]


In [20]:
r = np.random.permutation(np.arange(1,10))
r

array([4, 9, 6, 8, 5, 2, 1, 7, 3])

In [21]:
np.random.randint?

Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the `~numpy.random.Generator.integers`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values
size : int or tuple of ints, optional
    Outp

In [25]:
np.random.randint([1,2,3,4,5],[[10],[20],[10],[30],[20]])

array([[ 2,  8,  4,  9,  5],
       [ 9, 10, 16, 12,  7],
       [ 4,  6,  4,  4,  9],
       [ 5, 12, 13,  9, 19],
       [17, 10, 16, 17, 17]])