In [2]:
import matplotlib.pyplot as plt
import numpy as np

In [3]:
v = np.random.rand(1000)
v

array([7.80546210e-01, 5.01710698e-01, 7.38846082e-02, 8.39400199e-02,
       4.40649968e-01, 2.14547607e-01, 8.11871247e-01, 7.22127597e-01,
       3.01966887e-01, 1.67091398e-01, 8.91504203e-01, 7.20014902e-01,
       8.20748504e-01, 3.28779484e-01, 6.20102809e-01, 9.22513714e-01,
       5.65848473e-01, 4.55685478e-01, 2.99845522e-01, 3.68551311e-01,
       8.73249280e-01, 3.98924597e-01, 5.28920527e-01, 6.66139387e-01,
       2.65214840e-01, 8.56121793e-01, 8.69587378e-01, 5.19703818e-02,
       7.80080990e-02, 4.54658685e-01, 9.73536765e-01, 3.77108906e-01,
       6.96907390e-02, 5.55591450e-01, 6.86775245e-01, 1.13551197e-01,
       5.50686575e-01, 4.84612121e-01, 4.56408266e-01, 9.95975000e-01,
       6.34167220e-01, 6.43973056e-01, 6.66305077e-01, 7.31974545e-01,
       4.64809574e-01, 3.70744085e-01, 5.51808634e-01, 4.17014323e-01,
       5.26933770e-01, 9.58271839e-01, 3.07487132e-01, 7.44873304e-01,
       8.15441458e-01, 8.70513687e-03, 4.85536371e-01, 6.23728462e-01,
      

In [4]:
print(plt.hist(v,bins=100))

(array([10.,  8., 11.,  7.,  8., 13., 11.,  9.,  7.,  5., 13.,  9., 10.,
        9., 12., 10., 14.,  6.,  8., 11.,  9., 10., 16., 13.,  8., 10.,
        9.,  6., 11.,  8., 12., 15., 15.,  7., 13.,  8.,  9.,  7., 11.,
       18., 11., 12.,  7.,  6., 11., 10.,  8.,  6., 12.,  7.,  8., 18.,
       11., 11.,  9., 12.,  8., 10.,  9.,  8.,  8.,  9.,  9., 10., 13.,
       11., 11.,  9.,  8., 15., 13.,  9., 12., 11.,  6., 11., 12.,  8.,
       11.,  8., 12., 11., 10.,  5.,  9., 11., 10., 10., 13.,  8., 14.,
       10., 11.,  8.,  3.,  8.,  8.,  7.,  9., 19.]), array([3.63916293e-04, 1.03552757e-02, 2.03466351e-02, 3.03379945e-02,
       4.03293539e-02, 5.03207133e-02, 6.03120727e-02, 7.03034321e-02,
       8.02947915e-02, 9.02861509e-02, 1.00277510e-01, 1.10268870e-01,
       1.20260229e-01, 1.30251589e-01, 1.40242948e-01, 1.50234307e-01,
       1.60225667e-01, 1.70217026e-01, 1.80208386e-01, 1.90199745e-01,
       2.00191104e-01, 2.10182464e-01, 2.20173823e-01, 2.30165183e-01,
       2.401565

In [5]:
b = np.random.randn(100000)
plt.hist(b,bins=200)

(array([1.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        1.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 1.000e+00, 1.000e+00,
        3.000e+00, 2.000e+00, 1.000e+00, 0.000e+00, 3.000e+00, 2.000e+00,
        1.000e+00, 3.000e+00, 2.000e+00, 3.000e+00, 2.000e+00, 1.400e+01,
        4.000e+00, 7.000e+00, 6.000e+00, 1.400e+01, 6.000e+00, 7.000e+00,
        1.600e+01, 2.000e+01, 1.600e+01, 2.800e+01, 2.100e+01, 2.500e+01,
        3.400e+01, 3.300e+01, 4.400e+01, 4.000e+01, 4.100e+01, 6.000e+01,
        5.500e+01, 6.400e+01, 5.900e+01, 8.400e+01, 9.600e+01, 9.800e+01,
        1.100e+02, 1.360e+02, 1.270e+02, 1.460e+02, 1.700e+02, 1.680e+02,
        2.230e+02, 2.480e+02, 2.750e+02, 2.470e+02, 2.820e+02, 3.300e+02,
        3.610e+02, 3.720e+02, 4.130e+02, 4.150e+02, 4.370e+02, 4.640e+02,
        5.490e+02, 5.600e+02, 6.000e+02, 6.250e+02, 5.820e+02, 6.890e+02,
        7.690e+02, 7.970e+02, 8.410e+02, 8.700e+02, 9.360e+02, 9.900e+02,
        1.046e+03, 1.069e+03, 1.076e+0

In [6]:
a = np.arange(100)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [7]:
idx = np.argwhere(a==56)[0][0]
idx

56

In [8]:
s = np.round(10*np.random.rand(4,5))
s

array([[ 7.,  7.,  4.,  2.,  2.],
       [ 5.,  8.,  9.,  1.,  2.],
       [ 1.,  9., 10.,  8.,  2.],
       [ 4.,  4.,  3.,  4.,  8.]])

In [9]:
s[2]

array([ 1.,  9., 10.,  8.,  2.])

In [10]:
s[2][3]

8.0

In [11]:
s[2,3]

8.0

In [12]:
s[2,:]

array([ 1.,  9., 10.,  8.,  2.])

In [13]:
s[:2,2]

array([4., 9.])

In [14]:
a = np.arange(100)
b = a[a<40]

#### hstack() :- concatenate horizontally.
#### vstack() :- concatenate vertically.

In [15]:
c = np.hstack((a,b))
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99,  0,  1,
        2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39])

In [17]:
d = np.vstack((b,a))
d

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 40 and the array at index 1 has size 100

In [ ]:
d = np.arange(10000)
%timeit np.sum(d)
%timeit sum(d)

14.4 µs ± 6.92 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
1.31 ms ± 134 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
